services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library_app
    volumes:
      - .:/usr/src/app
      - ./storage:/usr/src/app
    ports:
      - "8000:8000"

    env_file:
      - .env

    environment:
      TZ: Asia/Tehran

    depends_on:
      - mysql_db
      - redis

    command: python main.py

  mysql_db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${DATABASE_NAME}
      TZ: Asia/Tehran
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    ports:
      - 3307:3306


  redis:
    image: redis:alpine
    container_name: redis_container
    ports:
      - 6379:6379


volumes:
  mysql_data:
