"""added is_returned

Revision ID: 55b81d0ae5e7
Revises: dca69135d3dd
Create Date: 2024-09-20 11:54:47.865931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55b81d0ae5e7'
down_revision: Union[str, None] = 'dca69135d3dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('is_returned', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'is_returned')
    # ### end Alembic commands ###
