"""create table role_permissions

Revision ID: 7edd4ddbbf6d
Revises: 55b81d0ae5e7
Create Date: 2024-09-21 15:28:28.766089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7edd4ddbbf6d'
down_revision: Union[str, None] = '55b81d0ae5e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permissions',
    sa.Column('permission_id', sa.BIGINT(), nullable=False),
    sa.Column('role_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('permission_id', 'role_id')
    )
    op.drop_constraint('permissions_ibfk_1', 'permissions', type_='foreignkey')
    op.drop_column('permissions', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('role_id', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('permissions_ibfk_1', 'permissions', 'roles', ['role_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_table('role_permissions')
    # ### end Alembic commands ###
