"""mapped return and loan date to Date

Revision ID: dca69135d3dd
Revises: dfd4a2563af6
Create Date: 2024-09-20 11:45:13.774504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dca69135d3dd'
down_revision: Union[str, None] = 'dfd4a2563af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
