"""Alter tables to InnoDB

Revision ID: dfd4a2563af6
Revises: b4255bac9c27
Create Date: 2024-09-19 17:28:07.860391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dfd4a2563af6'
down_revision: Union[str, None] = 'b4255bac9c27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'allowed_ips', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'books', 'categories', ['category_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'books', 'authors', ['author_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.alter_column('images', 'book_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.create_foreign_key(None, 'images', 'books', ['book_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'loans', 'books', ['book_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'loans', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'login_history', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'permissions', 'roles', ['role_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_constraint(None, 'login_history', type_='foreignkey')
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.alter_column('images', 'book_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint(None, 'allowed_ips', type_='foreignkey')
    # ### end Alembic commands ###
